name: ovmf-with-vbios

on:
  push:
  pull_request:
  workflow_dispatch:
#  schedule:
#    - cron: '0 0 * * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1.4.0
        with:
          age: '1 day'
          skip-recent: 4
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ovmf:
    needs: remove-old-artifacts
    runs-on: ubuntu-latest

    steps:
      # WARNING: Needed due to GitHub Actions disk space regression on Linux runners
      - name: Obtain maximum storage
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq) || true
          df -h

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build patched OVMF
        run: |
          ./bin/build.sh

      - name: Upload patched OVMF artifact
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: ovmf-patched
          path: build/ovmf-vbios-patched.tgz
